-- MySQL Script generated by MySQL Workbench
-- Fri Aug 25 12:30:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema registrohorario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema registrohorario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registrohorario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `registrohorario` ;

-- -----------------------------------------------------
-- Table `registrohorario`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registrohorario`.`administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `emailAdministrador` VARCHAR(45) NOT NULL,
  `contraseñaAdministrador` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla para almacenar credenciales de administración';


-- -----------------------------------------------------
-- Table `registrohorario`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registrohorario`.`departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombreDepartamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla para almacenar los distintos departamentos de la empresa';


-- -----------------------------------------------------
-- Table `registrohorario`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registrohorario`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `email_Usuario` VARCHAR(50) NOT NULL,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_departamento_idx` (`departamento` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla para almacenaje de usuarios o empleados que necesiten utilizar la app';


-- -----------------------------------------------------
-- Table `registrohorario`.`registroentrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registrohorario`.`registroentrada` (
  `idRegistroEntrada` INT NOT NULL AUTO_INCREMENT,
  `DateTiem` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_registroEntrada_Usuarios` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idRegistroEntrada`),
  INDEX `fk_registroEntrada_Usuarios_idx` (`fk_registroEntrada_Usuarios` ASC),
  CONSTRAINT `fk_registroEntrada_Usuarios`
    FOREIGN KEY (`fk_registroEntrada_Usuarios`)
    REFERENCES `registrohorario`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla para almacenar los registros de entrada de los usuarios registrados';


-- -----------------------------------------------------
-- Table `registrohorario`.`registrosalida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registrohorario`.`registrosalida` (
  `idRegistroSalida` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_registroSalida_Usuarios` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idRegistroSalida`),
  INDEX `fk_registroSalida_Usuarios_idx` (`fk_registroSalida_Usuarios` ASC),
  CONSTRAINT `fk_registroSalida_Usuarios`
    FOREIGN KEY (`fk_registroSalida_Usuarios`)
    REFERENCES `registrohorario`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla para almacenar los registros de salida de los usuarios registrados';


-- -----------------------------------------------------
-- Table `registrohorario`.`histórico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registrohorario`.`histórico` (
  `idHistorico` INT NOT NULL AUTO_INCREMENT,
  `fk_historico_usuarios` INT NULL DEFAULT NULL,
  `fk_historico_registroEntrada` INT NULL DEFAULT NULL,
  `fk_historico_registroSalida` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idHistorico`),
  INDEX `fk_historico_usuarios_idx` (`fk_historico_usuarios` ASC),
  INDEX `fk_historico_registroEntrada_idx` (`fk_historico_registroEntrada` ASC),
  INDEX `fk_historico_registroSalida_idx` (`fk_historico_registroSalida` ASC),
  CONSTRAINT `fk_historico_registroEntrada`
    FOREIGN KEY (`fk_historico_registroEntrada`)
    REFERENCES `registrohorario`.`registroentrada` (`idRegistroEntrada`),
  CONSTRAINT `fk_historico_registroSalida`
    FOREIGN KEY (`fk_historico_registroSalida`)
    REFERENCES `registrohorario`.`registrosalida` (`idRegistroSalida`),
  CONSTRAINT `fk_historico_usuarios`
    FOREIGN KEY (`fk_historico_usuarios`)
    REFERENCES `registrohorario`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla para relacionar todos los datos y que sean más sencillos de buscar';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
